name: Auto PR & Merge (with PAT)

on:
  workflow_dispatch:
    inputs:
      username:
        description: "GitHub username of the Co-author"
        required: true
        type: string

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Run create_pr.py
        env:
          PAT: ${{ secrets.PAT }}                             # ✅ lấy token từ secret
          INPUT_USERNAME: ${{ github.event.inputs.username }} # ✅ truyền username
        run: python scripts/create_pr.py
