name: Auto PR & Merge

on:
  workflow_dispatch:
    inputs:
      username:
        description: "GitHub Co-author"
        required: true
        type: string

jobs:
  create-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write      # Cho phép push, tạo nhánh, merge
      pull-requests: write # Cho phép merge PR
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Run auto PR script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    # token mặc định của Actions
          INPUT_USERNAME: ${{ github.event.inputs.username }}
        run: python scripts/create_pr.py
